baseurl = "http://blog.smerc.io/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    baseurl = "http://blog.smerc.io/"
    languageName = "English"
    title = "wow such blog"
    subtitle = "blogs for dayz amirite"
    owner = "@SmercatoRex"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      baseurl = "http://blog.smerc.io/"
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        baseurl = "http://blog.smerc.io/"
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        baseurl = "http://blog.smerc.io/"
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
