languageCode = "en-au"
languageName = "English"
displayName = ":flag-en:"
isoCode = "en"
weight = 1
rtl = false

title = "The Ogrengineered Blog"
description = "A blog featuring the ramblings of an engineer"
copyright = "&copy; 2022 smerc"

dateFormat = "2 January 2006"

[author]
  name = "smerc"
  image = "img/ogre.jpeg"
  headline = "an engineer with the heart of an ogre"
  bio = "An engineer with a background in private & cloud infrastructure, and various associated topcis :), also an ogre"
  links = [
    { twitter = "https://twitter.com/smercatoRex" }
  ]
